package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"testing"
)

// One line of testdata/cases.jsonl (generated by testdata/gen_cases.py). Null fields are not checked.
type phraseCase struct {
	Text           string  `json:"text"`
	Cat            string  `json:"cat"`
	LangHint       string  `json:"lang_hint"`
	ExpectRed      bool    `json:"expect_red"`
	ExpectPregnant *bool   `json:"expect_pregnant"`
	ExpectWeeks    *int    `json:"expect_weeks"`
	ExpectKB       *string `json:"expect_kb"` // "" = no entry with score >= 2 (a complaint must not get a KB answer)
	ExpectLang     *string `json:"expect_lang"`
	Src            string  `json:"src"`
	Note           string  `json:"note"`
}

// Minimum pass rate per category (whole case: every non-null expectation must hold).
// Clean-text emergencies (red_ru, red_kk, red_en) are not here: their expect_red must be 100%.
// Set after the rule fixes of 2026-09-30, a few points under the measured rate, so that a regression
// fails the test while the known leftovers (see the report in the commit / gen_cases.py notes) do not.
var minPassRate = map[string]float64{
	"red_ru":         1.00, // whole case, incl. language
	"red_kk":         1.00,
	"red_en":         1.00,
	"red_mix":        0.95, // ru+kk in one message
	"red_noisy":      0.90, // caps, no Kazakh letters, typos: arbitrary typos stay for the LLM
	"red_translit":   0.80, // Latin transliteration: a small explicit rule set, not a transliterator
	"red_preg":       0.95,
	"red_preg_mix":   0.95,
	"not_red":        0.90, // false-red traps: breast/chest context split by a comma stays red (safe side)
	"not_red_nopreg": 1.00,
	"preg_detect":    0.95,
	"preg_negative":  0.95,
	"kb":             0.90,
	"kb_preg":        0.90,
	"kb_none":        0.95,
	"lang":           0.90,
}

func TestThousandCases(t *testing.T) {
	tr, err := LoadTriage("../triage_rules.json")
	if err != nil {
		t.Fatal(err)
	}
	kb, err := LoadKnowledge("../knowledge.json")
	if err != nil {
		t.Fatal(err)
	}
	f, err := os.Open("testdata/cases.jsonl")
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()

	type stat struct{ total, passed int }
	cats := map[string]*stat{}
	checks := map[string]*stat{} // per check kind: red, preg, weeks, lang, kb
	var failures []string
	strictTotal, strictPassed := 0, 0

	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	line := 0
	for sc.Scan() {
		line++
		if strings.TrimSpace(sc.Text()) == "" {
			continue
		}
		var c phraseCase
		if err := json.Unmarshal(sc.Bytes(), &c); err != nil {
			t.Fatalf("cases.jsonl:%d: %v", line, err)
		}
		var why []string
		check := func(kind string, ok bool, msg string) {
			s := checks[kind]
			if s == nil {
				s = &stat{}
				checks[kind] = s
			}
			s.total++
			if ok {
				s.passed++
			} else {
				why = append(why, msg)
			}
		}

		pregnant, weeks := DetectPregnancy(c.Text)
		phrase, _, red := tr.CheckRed(c.Text, pregnant)
		if red != c.ExpectRed {
			msg := "red=false, want true"
			if red {
				msg = fmt.Sprintf("red=true (%q), want false", phrase)
			}
			check("red", false, msg)
		} else {
			check("red", true, "")
		}
		if c.Cat == "red_ru" || c.Cat == "red_kk" || c.Cat == "red_en" {
			if c.ExpectRed {
				strictTotal++
				if red {
					strictPassed++
				}
			}
		}
		if c.ExpectPregnant != nil {
			check("preg", pregnant == *c.ExpectPregnant, fmt.Sprintf("pregnant=%v, want %v", pregnant, *c.ExpectPregnant))
		}
		if c.ExpectWeeks != nil {
			got := 0
			if weeks != nil {
				got = *weeks
			}
			check("weeks", got == *c.ExpectWeeks, fmt.Sprintf("weeks=%d, want %d", got, *c.ExpectWeeks))
		}
		if c.ExpectLang != nil {
			got := detectLanguage(c.Text)
			check("lang", got == *c.ExpectLang, fmt.Sprintf("lang=%q, want %q", got, *c.ExpectLang))
		}
		if c.ExpectKB != nil {
			// as in chat.go: preg_* entries only when the pregnancy flag is set
			pregOK := func(e *KBEntry) bool { return pregnant || !strings.HasPrefix(e.ID, "preg_") }
			e, score := kb.Search(c.Text, pregOK)
			id := ""
			if e != nil {
				id = e.ID
			}
			if *c.ExpectKB == "" {
				check("kb", e == nil || score < 2, fmt.Sprintf("kb=%s(score %d), want no KB answer (<2)", id, score))
			} else {
				check("kb", id == *c.ExpectKB, fmt.Sprintf("kb=%q(score %d), want %q", id, score, *c.ExpectKB))
			}
		}

		s := cats[c.Cat]
		if s == nil {
			s = &stat{}
			cats[c.Cat] = s
		}
		s.total++
		if len(why) == 0 {
			s.passed++
		} else {
			failures = append(failures, fmt.Sprintf("%-14s %-8s %q: %s", c.Cat, c.LangHint, c.Text, strings.Join(why, "; ")))
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}

	names := make([]string, 0, len(cats))
	for n := range cats {
		names = append(names, n)
	}
	sort.Strings(names)
	var b strings.Builder
	fmt.Fprintf(&b, "\n%-16s %6s %6s %6s %7s %7s\n", "category", "total", "passed", "failed", "rate", "min")
	all, allPassed := 0, 0
	for _, n := range names {
		s := cats[n]
		all += s.total
		allPassed += s.passed
		fmt.Fprintf(&b, "%-16s %6d %6d %6d %6.1f%% %6.0f%%\n", n, s.total, s.passed, s.total-s.passed,
			100*float64(s.passed)/float64(s.total), 100*minPassRate[n])
	}
	fmt.Fprintf(&b, "%-16s %6d %6d %6d %6.1f%%\n", "ALL", all, allPassed, all-allPassed, 100*float64(allPassed)/float64(all))
	fmt.Fprintf(&b, "\nper check:")
	for _, k := range []string{"red", "preg", "weeks", "lang", "kb"} {
		if s := checks[k]; s != nil {
			fmt.Fprintf(&b, "  %s %d/%d", k, s.passed, s.total)
		}
	}
	fmt.Fprintf(&b, "\nclean-text emergencies (red_ru/kk/en, expect_red): %d/%d\n", strictPassed, strictTotal)
	if len(failures) > 0 {
		fmt.Fprintf(&b, "\nfirst failures (%d total):\n", len(failures))
		for i, s := range failures {
			if i == 40 && os.Getenv("CASES_ALL") == "" { // CASES_ALL=1 prints every failure
				break
			}
			b.WriteString("  " + s + "\n")
		}
	}
	t.Log(b.String())

	if strictPassed != strictTotal {
		t.Errorf("clean-text emergencies: %d/%d detected, want 100%%", strictPassed, strictTotal)
	}
	for _, n := range names {
		s := cats[n]
		min, ok := minPassRate[n]
		if !ok {
			t.Errorf("category %q has no threshold in minPassRate", n)
			continue
		}
		if rate := float64(s.passed) / float64(s.total); rate < min {
			t.Errorf("%s: pass rate %.1f%% below %.0f%%", n, 100*rate, 100*min)
		}
	}
}
